[package]
name = "cloud-entertainment/game-analytics-sdk"
description = "Modified GameAnalytics Roblox SDK that works in Studio"
version = "2.2.3"
realm = "shared"
registry = "https://github.com/Cloud-Entertainment/wally-index"
exclude = ["ExampleProject", "wally.exe", "aftman", "*.zip"]

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"